# Generated by Django 4.2.11 on 2024-10-14 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("project", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("add_by", models.IntegerField()),
                (
                    "add_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Create Date"),
                ),
                ("modify_by", models.IntegerField()),
                (
                    "modify_at",
                    models.DateTimeField(auto_now=True, verbose_name="Update Date"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("owner", models.IntegerField()),
                ("on_behalf", models.IntegerField(null=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("to_do", "To Do"),
                            ("in_progress", "In Progress"),
                            ("review", "Review"),
                            ("completed", "Completed"),
                        ],
                        default="to_do",
                        max_length=20,
                    ),
                ),
                (
                    "progress",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                ("due_date", models.DateField(blank=True, null=True)),
                (
                    "milestone",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tasks",
                        to="project.milestone",
                    ),
                ),
            ],
            options={
                "db_table": "task_task",
            },
        ),
    ]
