# Generated by Django 4.2.11 on 2024-10-14 14:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("add_by", models.IntegerField()),
                (
                    "add_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Create Date"),
                ),
                ("modify_by", models.IntegerField()),
                (
                    "modify_at",
                    models.DateTimeField(auto_now=True, verbose_name="Update Date"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("owner", models.IntegerField()),
                ("on_behalf", models.IntegerField(null=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("start_date", models.DateField(default=datetime.date(2024, 10, 14))),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("received", "Received"),
                            ("in_progress", "In Progress"),
                            ("on_hold", "On Hold"),
                            ("completed", "Completed"),
                        ],
                        default="received",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "db_table": "project_project",
            },
        ),
        migrations.CreateModel(
            name="Milestone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("add_by", models.IntegerField()),
                (
                    "add_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Create Date"),
                ),
                ("modify_by", models.IntegerField()),
                (
                    "modify_at",
                    models.DateTimeField(auto_now=True, verbose_name="Update Date"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("owner", models.IntegerField()),
                ("on_behalf", models.IntegerField(null=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("due_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "budget",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="milestones",
                        to="project.project",
                    ),
                ),
            ],
            options={
                "db_table": "project_milestone",
            },
        ),
    ]
